<?php
namespace Hbase;

/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Hbase_append_args extends TBase
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'append',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Hbase\TAppend',
        ),
    );

    /**
     * The single append operation to apply
     * 
     * @var \Hbase\TAppend
     */
    public $append = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'Hbase_append_args';
    }


    public function read($input)
    {
        return $this->_read('Hbase_append_args', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('Hbase_append_args', self::$_TSPEC, $output);
    }

}
