<?php
namespace Hbase;

/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * A Mutation object is used to either update or delete a column-value.
 */
class Mutation extends TBase
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'isDelete',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        2 => array(
            'var' => 'column',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'value',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'writeToWAL',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
    );

    /**
     * @var bool
     */
    public $isDelete = false;
    /**
     * @var string
     */
    public $column = null;
    /**
     * @var string
     */
    public $value = null;
    /**
     * @var bool
     */
    public $writeToWAL = true;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'Mutation';
    }


    public function read($input)
    {
        return $this->_read('Mutation', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('Mutation', self::$_TSPEC, $output);
    }

}
