<?php
namespace Hbase;

/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Holds column name and the cell.
 */
class TColumn extends TBase
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'columnName',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'cell',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Hbase\TCell',
        ),
    );

    /**
     * @var string
     */
    public $columnName = null;
    /**
     * @var \Hbase\TCell
     */
    public $cell = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'TColumn';
    }


    public function read($input)
    {
        return $this->_read('TColumn', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('TColumn', self::$_TSPEC, $output);
    }

}
